## Notebook for Manual Analysis of Generated Tables

In [1]:
import pandas as pd
import numpy as np
import json
from utils.utils import *
import pprint
from eval.eval import *
from post_processing.post_processing import *
from utils.table_utils import *
from model_inference.gpt import *
from model_inference.llama import *
from model_inference.gemini import *
eval_rows = 728
model_output_file = "./model_outputs/llama_baseline_2610_117AM/tables_gpt_trial.json"
statements ="./model_outputs/llama_baseline_2610_117AM/ai_response.json"
headers = "./model_outputs/llama_baseline_2610_117AM/headers.json"
gold_table_file = "./data/rotowire/test.text"

In [2]:
statements = read_file(statements)
headers = read_file(headers)

In [3]:
### Reading Gold Labels
gold_texts = []
with open(gold_table_file,"r") as f:
    lines = [line.strip() for line in f.readlines()]

In [4]:

## Read outputs from files.
# with open(model_output_file,'r') as f:
#      output = json.load(f)
# extracted_tables = extract_tables_from_responses(output) 
# if reading and extractind directly from gpt model.  
# if model responses are saved and read from a file, helpful for testing and multiple evaluations.
# output_tables_strucbench = generate_output_lines(output_path ='../data/strucbench/table/test.data',end_line= eval_rows) ### gold tables
output_tables_rotowire = generate_output_lines(output_path='./data/rotowire/test.data',end_line = eval_rows)
#print(extracted_tables)

# Now you can process each extracted table

gold_table_player_strucbench = []
gold_table_team_strucbench = []
gold_table_player_rotowire = []
gold_table_team_rotowire = []
model_output_team = []
model_output_player = []

count = 0
# for model_output,gold_label_rotowire,gold_label_strucbench in zip(extracted_tables,output_tables_rotowire,output_tables_strucbench):
for gold_label_rotowire in output_tables_rotowire:

    #data_point = tables['data_point']
    

     gold_tables_rotowire = separate_tables(gold_label_rotowire)
     # gold_tables_strucbench = separate_tables(gold_label_strucbench)
     # print(gold_tables_strucbench)
     # print(gold_tables_rotowire)
     # try: 
     #      model_output_tt = prune_table(model_output['Team'])
     # except:
     #      model_output_tt = ""
     # try:     
     #      model_output_pt = prune_table(model_output['Player'])
     # except:
     #      model_output_pt = ""

     #model_tables = separate_tables(model_output.strip(['Final Answer','\n',':')])
     #print(model_tables)
     # print(model_tables['Player'])
     # print("--------------------------")
     # print(model_tables['Team'])
     #print("---------------------------")
     #print(gold_tables['Player'])
     #print("---------------------------")
     #print(gold_tables['Team'])
     #print("---------------------------")

     # model_output_team.append(model_output_tt)
     # model_output_player.append(model_output_pt) 
     # if 'Player' not in gold_tables_strucbench.keys():
     #      print(gold_label_strucbench)

     gold_table_player_rotowire.append(gold_tables_rotowire['Player'])
     gold_table_team_rotowire.append(gold_tables_rotowire['Team'])
     # gold_table_player_strucbench.append(gold_tables_strucbench['Player'])
     # gold_table_team_strucbench.append(gold_tables_strucbench['Team'])
    #  count += 1

In [5]:
### Reading Gold Labels
gold_texts = []
with open(gold_table_file,"r") as f:
    lines = [line.strip() for line in f.readlines()]

In [740]:
idx = 364

In [741]:
%clear
import textwrap
print(textwrap.fill(lines[idx],width=100))

The Los Angeles Clippers defeated the Charlotte Hornets in OT 124 - 121 at Staples Center on Sunday.
The Clippers (36 - 23) are still tied with the Memphis Grizzlies for the 5 - seed in the Western
Conference, but pulled out a needed win with opening day starters on the court. Kemba Walker single
handedly took the Hornets (25 - 34) to overtime after draining a 25 - foot three - pointer to bring
the game within two points with :36 remaining in the fourth quarter, and then finished the job at
the free throw line on the next possession to tie the game at 113 points a piece. In OT, both teams
went back - and - forth during the first two minutes, but the Hornets Marvin Williams fouled Blake
Griffin and put him on the line to give the Clippers a one point lead. Walker's heroics at the end
of the fourth quarter will be overshadowed by a bad pass that was stolen by DeAndre Jordan, who also
finished with a dunk on the other end with a few ticks left on the clock. Blake Griffin had a
monsterous game evidenced by his 43 points, 10 rebounds, five assists and two steals on 15 - of - 26
shooting across 42 minutes. Chris Paul and DeAndre Jordan also stacked the box score. The Clippers
star point guard finished with 15 points, 17 assists and nine rebounds, while Jordan scored 20
points and hauled in 19 rebounds. J.J. Reddick scored 19 points in the first half, but had trouble
continuing the hot hand in the second half. Reddick finished with 22 points on 3 - of - 7 shooting
from behind the arc. Kemba Walker and Nicolas Batum led the Hornets in scoring with 34 points and 31
points, respectively, while Jeremy Lamb was effective off the bench in his 37 minutes of action.
Batum was more well rounded in his performance and added eight rebounds and four assists. Next up,
the Hornets host the Los Angeles Lakers on Tuesday, while the Clippers visit the Houston Rockets on
Wednesday.

In [742]:
# input = statements[idx]['response']
# header = headers[idx]['response']
# lol = dict()
# lmao_dict = []
# tex = header + input
# tex = tex.strip('\n')
# lmao =ask_chatgpt(text=tex,prompt_path="prompts/rotowire_gpt4o_make_tables.txt")
# lol['response'] = lmao
# lmao_dict.append(lol)
# #pprint.pprint(lmao)
# tables = extract_tables_from_responses(lmao_dict)

In [743]:
team_df = convert_to_df(gold_table_team_rotowire[idx])
team_df

            Losses Total points Wins
0  Clippers     23          124   36
1   Hornets     34          121   25

In [744]:
player_df = convert_to_df(gold_table_player_rotowire[idx])
player_df

,,Assists,Field goals attempted,Field goals made,Minutes played,Points,Total rebounds,Steals
0,Nicolas Batum,4,,,,31,8,
1,Kemba Walker,,,,,34,,
2,Jeremy Lamb,,,,37,,,
3,Blake Griffin,5,26,15,42,43,10,2
4,DeAndre Jordan,,,,,20,19,

In [745]:
if team_df is not None:
    team_df.to_csv(f'data/rotowire_corrected/team/{idx}.csv',index = False, header = True)
if player_df is not None:
    player_df.to_csv(f'data/rotowire_corrected/player/{idx}.csv',index=False, header = True)

In [655]:
convert_to_df(tables[0]['Team'])

NameError: name 'tables' is not defined

In [ ]:
211convert_to_df(tables[0]['Team'])

NameError: name 'tables' is not defined

In [273]:
convert_to_df(tables[0]['Player'])

             Player Points Assists Rebounds Turnovers Shooting
0         John Wall     22      13        5         7
1  D'Angelo Russell     22
2     Marcin Gortat     16               10
3       Kobe Bryant     17       2        1            6-of-15

In [367]:
te = """ The Cleveland Cavaliers completed their sweep of the Boston Celtics with a 101-93 win on Sunday.
The Cleveland Cavaliers entered the game with a 3-0 lead in the series.
The Cleveland Cavaliers won both of the first two quarters to take a 57-36 lead at halftime.
Coach David Blatt chose to play his key players for most of the game to ensure a win.
LeBron James played 46 minutes in the game.
Kyrie Irving played 43 minutes in the game.
Kevin Love was forced from the game in the first quarter with a dislocated left shoulder.
Kelly Olynyk pulled down on Kevin Love's arm while fighting for a rebound, causing Love's injury.
Kendrick Perkins put a hard screen on Jae Crowder in the second quarter.
Kendrick Perkins was assessed a technical foul and a flagrant-1 foul for his actions.
Jae Crowder was assessed a technical foul for his response to Kendrick Perkins' screen.
J.R. Smith hit Jae Crowder in the face with a backhand in the third quarter.
J.R. Smith was given a flagrant-2 foul and automatically ejected from the game.
Jae Crowder injured his knee during the J.R. Smith incident and left the game.
Jae Crowder suffered a left knee sprain and was unable to return to the game.
The Boston Celtics outscored the Cleveland Cavaliers 25-13 in the third quarter.
The Cleveland Cavaliers carried a nine-point lead into the fourth quarter.
The Cleveland Cavaliers never let the Boston Celtics get closer than a six-point divide in the fourth quarter.
The Cleveland Cavaliers will advance to the Eastern Conference semifinals.
The Cleveland Cavaliers will play the winner of the Bulls/Bucks series in the Eastern Conference semifinals.
Kevin Love's status will be updated after he undergoes tests with the team's doctors.
J.R. Smith and Kendrick Perkins appear in line for suspensions for their actions in the game. 
Table Headers:
{
    "Team" : {
        "row_headers" : ["Cleveland Cavaliers", "Boston Celtics"],
        "column_headers" : ["Final Score", "Series Lead", "Half Time Score", "Third Quarter Score", "Fourth Quarter Score", "Advancement", "Next Opponent"]
    },
    "Player" : {
        "row_headers" : ["LeBron James", "Kyrie Irving", "Kevin Love", "Kelly Olynyk", "Kendrick Perkins", "Jae Crowder", "J.R. Smith"],
        "col_headers" : ["Minutes Played", "Injury Status", "Fouls", "Ejection Status", "Suspension Status"]
    }
}
"""

In [ ]:
pprint.pprint(ask_chatgpt(text=(input+header)('\n').strip('\ '),prompt_path="prompts/rotowire_gpt4o_make_tables.txt"))

In [ ]:
pprint.pprint(ask_gemini(
    prompt_path="prompts/rotowire_prompt_verify.txt",
    text= te.strip('\n')
))

In [ ]:
pprint.pprint(output[idx]['response'])

In [ ]:
pprint.pprint(output[idx]['input'])

In [ ]:
pprint.pprint(output[idx]['response'])

In [ ]:
df = convert_to_df(model_output_player[idx])
from tabulate import tabulate
print(tabulate(df, headers='keys', tablefmt='pretty'))
print(df)

In [ ]:
convert_to_df(gold_table_player[idx])

In [ ]:
convert_to_df(model_output_team[idx])

In [ ]:
convert_to_df(gold_table_team[idx])

In [ ]:
for i in range(0,50):
    print(i,custom_compare_tables(model_output_player[i],gold_table_player[i]))

In [ ]:
for i in range(0,50):
    print(i,compare_values(model_output_player[i],gold_table_player[i]))

## Team Table Compare

In [ ]:
for i in range(0,50):
    print(i,custom_compare_tables(model_output_team[i],gold_table_team[i]))

In [ ]:
for i in range(0,50):
    print(i,compare_values(model_output_team[i],gold_table_team[i]))