## Notebook for Manual Analysis of Generated Tables

In [1]:
import pandas as pd
import numpy as np
import json
from utils.utils import *
import pprint
from eval.eval import *
from post_processing.post_processing import *
from utils.table_utils import *
from model_inference.gpt import *
from model_inference.llama import *
from model_inference.gemini import *
eval_rows = 728
gold_text_file = "./data/wikibio/test.text"
gold_table_file = "./data/wikibio/test.text"

In [2]:
statements = read_file(gold_text_file)

In [3]:
### Reading Gold Labels
gold_texts = []
with open(gold_table_file,"r") as f:
    lines = [line.strip() for line in f.readlines()]

In [4]:
gold_tabels_wikibio = generate_output_lines(output_path='./data/wikibio/test.data',end_line = eval_rows)
model_output_wikibio = []
parsed_tables_wikibio = []
count = 0

# for model_output,gold_label_rotowire,gold_label_strucbench in zip(extracted_tables,output_tables_rotowire,output_tables_strucbench):
for table in gold_tabels_wikibio:
     table = parse_text_to_table(table)
     parsed_tables_wikibio.append(table)

In [5]:
idx = 1

In [6]:
%clear
import textwrap
print(textwrap.fill(lines[idx],width=100))

philippe adnot (born 25 august 1945 in rhèges) is a member of the senate of france. he was first
elected in 1989, and represents the aube department. a farmer by profession, he serves as an
independent, and also serves as the head of the general council of aube, to which he was elected to
represent the canton of méry-sur-seine in 1980. in 1998 and 2008, he was re-elected to the senate in
the first round, avoiding the need for a run-off vote. having contributed to the creation of the
university of technology of troyes, in 1998 he was made the first vice president of the university
board, of which he is currently the president. he is a member of the senate's committee on the laws
relating to the freedoms and responsibilities of universities. as of 2009, he serves as the delegate
from the administrative meeting for senators not on the list of another group he is decorated as a
chevalier of the ordre national de mérite agricole.

In [7]:
parsed_tables_wikibio[idx]

      Attribute                          Value
0   birth place                         france
1    occupation                         farmer
2     residence                         france
3    birth date                 25 august 1945
4  constituency  aube canton de méry-sur-seine
5          name                 philippe adnot

In [8]:
input = statements[idx] 
lol = dict()
lmao_dict = []
tex = input.strip('\n')
lmao =ask_chatgpt(text=tex,prompt_path="prompts/wikibio.txt")
lol['response'] = lmao
lmao_dict.append(lol)

In [14]:
# Replace literal \n with actual newline characters
data = lmao.replace('\\n', '\n')

# Split the string into lines
lines = data.split('\n')

# Split each line into attribute and value
pairs = [line.split(',', 1) for line in lines]

# Create DataFrame
df = pd.DataFrame(pairs, columns=['Attribute', 'Value'])

# Display the DataFrame
print(df)

                         Attribute  \
0                       "Attribute
1                             Name
2                    Date of Birth
3                   Place of Birth
4                         Position
5                    First Elected
6                       Represents
7                       Profession
8            Political Affiliation
9      Position in General Council
10      Elected to General Council
11              Canton Represented
12            Re-elected to Senate
13              Re-election Method
14                    Contribution
15          Position at University
16  Current Position at University
17            Committee Membership
18                   Delegate Role
19                      Decoration

                                                Value
0                                               Value
1                                      Philippe Adnot
2                                      25 August 1945
3                                              Rhèges
4                      Member of the Senate of France
5                                                1989
6                                     Aube Department
7                                              Farmer
8                                         Independent
9                 Head of the General Council of Aube
10                                               1980
11                                     Méry-sur-Seine
12                                      1998 and 2008
13                                        First Round
14  Creation of the University of Technology of Tr...
15       First Vice President of the University Board
16                                          President
17  SENATE's Committee on the Laws Relating to the...
18  Delegate from the Administrative Meeting for S...
19  CHEVALIER of the Ordre National de Mérite Agri...

In [15]:
df

,Attribute,Value
0,"""Attribute",Value
1,Name,Philippe Adnot
2,Date of Birth,25 August 1945
3,Place of Birth,Rhèges
4,Position,Member of the Senate of France
5,First Elected,1989
6,Represents,Aube Department
7,Profession,Farmer
8,Political Affiliation,Independent
9,Position in General Council,Head of the General Council of Aube
10,Elected to General Council,1980
11,Canton Represented,Méry-sur-Seine
12,Re-elected to Senate,1998 and 2008
13,Re-election Method,First Round
14,Contribution,Creation of the University of Technology of Tr...
15,Position at University,First Vice President of the University Board
16,Current Position at University,President
17,Committee Membership,SENATE's Committee on the Laws Relating to the...
18,Delegate Role,Delegate from the Administrative Meeting for S...
19,Decoration,CHEVALIER of the Ordre National de Mérite Agri...

In [30]:
lmao = lmao.strip('"')
lmao = lmao.strip("'")
pprint.pprint(lmao)

('Attribute,Value\n'
 'Name,Philippe Adnot\n'
 'Date of Birth,25 August 1945\n'
 'Place of Birth,Rhèges\n'
 'Position,Member of the Senate of France\n'
 'First Elected,1989\n'
 'Represents,Aube Department\n'
 'Profession,Farmer\n'
 'Political Affiliation,Independent\n'
 'Position in General Council,Head of the General Council of Aube\n'
 'Elected to General Council,1980\n'
 'Canton Represented,Méry-sur-Seine\n'
 'Re-elections to Senate,1998, 2008\n'
 'Re-election Method,First Round\n'
 'Contribution,Creation of the University of Technology of Troyes\n'
 'Position at University,First Vice President of the University Board\n'
 'Current Position at University,President\n'
 "Committee Membership,Senate's Committee on the Laws Relating to the Freedoms "
 'and Responsibilities of Universities\n'
 'Delegate Status,Delegate from the Administrative Meeting for Senators not on '
 'the List of Another Group\n'
 'Decoration,Chevailer of the Ordre National de Mérite Agricole')

In [26]:
pd.DataFrame(lmao)

ValueError: DataFrame constructor not properly called!