## Notebook for Manual Analysis of Generated Tables

In [1]:
import pandas as pd
import numpy as np
import json
from utils.utils import *
import pprint
from eval.eval import *
from post_processing.post_processing import *
from utils.table_utils import *
from model_inference.gpt import *
from model_inference.llama import *
from model_inference.gemini import *
eval_rows = 725
model_output_file = "./model_outputs/llama_baseline_2610_117AM/tables_gpt_trial.json"
statements ="./model_outputs/llama_baseline_2610_117AM/ai_response.json"
headers = "./model_outputs/llama_baseline_2610_117AM/headers.json"
gold_table_file = "../data/rotowire/test.text"

In [2]:
statements = read_file(statements)
headers = read_file(headers)

In [3]:
### Reading Gold Labels
gold_texts = []
with open(gold_table_file,"r") as f:
    lines = [line.strip() for line in f.readlines()]

In [4]:

## Read outputs from files.
# with open(model_output_file,'r') as f:
#      output = json.load(f)
# extracted_tables = extract_tables_from_responses(output) 
# if reading and extractind directly from gpt model.  
# if model responses are saved and read from a file, helpful for testing and multiple evaluations.
output_tables_strucbench = generate_output_lines(output_path ='data/strucbench/table/test.data',end_line= eval_rows) ### gold tables
output_tables_rotowire = generate_output_lines(output_path='data/rotowire/test.data',end_line = eval_rows)
#print(extracted_tables)

# Now you can process each extracted table

gold_table_player_strucbench = []
gold_table_team_strucbench = []
gold_table_player_rotowire = []
gold_table_team_rotowire = []
model_output_team = []
model_output_player = []

count = 0
# for model_output,gold_label_rotowire,gold_label_strucbench in zip(extracted_tables,output_tables_rotowire,output_tables_strucbench):
for gold_label_rotowire,gold_label_strucbench in zip(output_tables_rotowire,output_tables_strucbench):

    #data_point = tables['data_point']

     gold_tables_rotowire = separate_tables(gold_label_rotowire)
     gold_tables_strucbench = separate_tables(gold_label_strucbench)
     # print(gold_tables_strucbench)
     # print(gold_tables_rotowire)
     if 'Team' not in gold_tables_rotowire or 'Team' not in gold_tables_strucbench or 'Player' not in gold_tables_rotowire or 'Player' not in gold_tables_strucbench:
          count += 1
          continue
     # try: 
     #      model_output_tt = prune_table(model_output['Team'])
     # except:
     #      model_output_tt = ""
     # try:     
     #      model_output_pt = prune_table(model_output['Player'])
     # except:
     #      model_output_pt = ""

     #model_tables = separate_tables(model_output.strip(['Final Answer','\n',':')])
     #print(model_tables)
     # print(model_tables['Player'])
     # print("--------------------------")
     # print(model_tables['Team'])
     #print("---------------------------")
     #print(gold_tables['Player'])
     #print("---------------------------")
     #print(gold_tables['Team'])
     #print("---------------------------")

     # model_output_team.append(model_output_tt)
     # model_output_player.append(model_output_pt) 
     # if 'Player' not in gold_tables_strucbench.keys():
     #      print(gold_label_strucbench)

     gold_table_player_rotowire.append(gold_tables_rotowire['Player'])
     gold_table_team_rotowire.append(gold_tables_rotowire['Team'])
     gold_table_player_strucbench.append(gold_tables_strucbench['Player'])
     gold_table_team_strucbench.append(gold_tables_strucbench['Team'])

In [5]:
### Reading Gold Labels
gold_texts = []
with open(gold_table_file,"r") as f:
    lines = [line.strip() for line in f.readlines()]

In [6]:
idx = 0

In [7]:
%clear
import textwrap
print(textwrap.fill(lines[idx],width=100))

The Atlanta Hawks (46 - 12) beat the Orlando Magic (19 - 41) 95 - 88 on Friday. Al Horford had a
good all - around game, putting up 17 points, 13 rebounds, four assists and two steals in a tough
matchup against Nikola Vucevic. Kyle Korver was the lone Atlanta starter not to reach double figures
in points. Jeff Teague bounced back from an illness, he scored 17 points to go along with seven
assists and two steals. After a rough start to the month, the Hawks have won three straight and sit
atop the Eastern Conference with a nine game lead on the second place Toronto Raptors. The Magic
lost in devastating fashion to the Miami Heat in overtime Wednesday. They blew a seven point lead
with 43 seconds remaining and they might have carried that with them into Friday's contest against
the Hawks. Vucevic led the Magic with 21 points and 15 rebounds. Aaron Gordon (ankle) and Evan
Fournier (hip) were unable to play due to injury. The Magic have four teams between them and the
eighth and final playoff spot in the Eastern Conference. The Magic will host the Charlotte Hornets
on Sunday, and the Hawks with take on the Heat in Miami on Saturday.

In [8]:
input = statements[idx]['response']
header = headers[idx]['response']
lol = dict()
lmao_dict = []
tex = header + input
tex = tex.strip('\n')
lmao =ask_chatgpt(text=tex,prompt_path="prompts/rotowire_gpt4o_make_tables.txt")
lol['response'] = lmao
lmao_dict.append(lol)
pprint.pprint(lmao)
tables = extract_tables_from_responses(lmao_dict)

('Final Answer: Team: <NEWLINE> | Final Score | Series Lead | Half Time Score '
 '| Third Quarter Score | Fourth Quarter Score | Advancement | Next Opponent | '
 '<NEWLINE> | Cleveland Cavaliers | 101 | 4-0 | 57-36 | 13 | 31 | Eastern '
 'Conference semifinals | Winner of Bulls/Bucks series | <NEWLINE> | Boston '
 'Celtics | 93 |  |  | 25 | 25 |  |  | <NEWLINE> <ENDTABLE> Player: <NEWLINE> '
 '| Minutes Played | Injury Status | Fouls | Ejection Status | Suspension '
 'Status | <NEWLINE> | LeBron James | 46 |  |  |  |  | <NEWLINE> | Kyrie '
 'Irving | 43 |  |  |  |  | <NEWLINE> | Kevin Love |  | Dislocated left '
 'shoulder |  |  |  | <NEWLINE> | Kelly Olynyk |  |  |  |  |  | <NEWLINE> | '
 'Kendrick Perkins |  |  | Technical foul, Flagrant-1 |  | Appears likely | '
 '<NEWLINE> | Jae Crowder |  | Left knee sprain | Technical foul | Ejected | '
 'Appears likely | <NEWLINE> | J.R. Smith |  |  | Flagrant-2 | Ejected | '
 'Appears likely | <NEWLINE> <ENDTABLE>')
Table 'Team' found for data_point 0
Table 'Player' found for data_point 0

In [9]:
convert_to_df(gold_table_team_rotowire[idx])

          Percentage of field goals Losses Total points Rebounds Wins
0  Knicks                        41     31           82       36    5
1   Bucks                        46     17           95       48   18

In [10]:
convert_to_df(tables[0]['Player'])

     Minutes Played Injury Status                     Fouls  \
0      LeBron James            46
1      Kyrie Irving            43
2        Kevin Love                Dislocated left shoulder
3      Kelly Olynyk
4  Kendrick Perkins
5       Jae Crowder                        Left knee sprain
6        J.R. Smith

              Ejection Status Suspension Status
0
1
2
3
4  Technical foul, Flagrant-1                    Appears likely
5              Technical foul           Ejected  Appears likely
6                  Flagrant-2           Ejected  Appears likely

In [11]:
convert_to_df(gold_table_team_rotowire[idx])

             Percentage of field goals Losses Total points  \
0    Celtics                                4           93
1  Cavaliers                        40                 101

  Points in 3rd quarter Wins
0                    25    0
1                    13

In [12]:
convert_to_df(gold_table_player_rotowire[idx])

                         Assists Defensive rebounds 3-pointers attempted  \
0  Giannis Antetokounmpo                                               1
1          Zaza Pachulia
2         Brandon Knight       5                                       3
3       Kendall Marshall
4               JR Smith
5           Cole Aldrich
6       Tim Hardaway Jr.       4                  3                    5
7            Jason Smith

  3-pointers made Field goals attempted Field goals made  \
0               1                     9                6
1                                    12                6
2               1                    14                6
3                                     8                6
4
5                                    10                6
6               3                    13                6
7                                    11                3

  Free throws attempted Free throws made Minutes played Personal fouls Points  \
0                     6                3                                   16
1                     4                4                                   16
2                                                                          17
3                     3                3                                   15
4                                                    37              2     15
5                                                                          12
6                     4                                              3     17
7                     4                4                                   10

  Total rebounds Turnovers
0             12
1             14
2                        3
3
4              7         2
5              7
6              3
7

In [13]:
convert_to_df(gold_table_team_strucbench[idx])

          Percentage of field goals Losses Total points Rebounds Wins
0  Knicks                        41     31           82       36    5
1   Bucks                        46     17           95       48   18

In [14]:
convert_to_df(gold_table_player_strucbench[idx])

,,Assists,Defensive rebounds,3-pointers attempted,3-pointers made,Field goals attempted,Field goals made,Free throws attempted,Free throws made,Minutes played,Personal fouls,Points,Total rebounds,Turnovers
0,Giannis Antetokounmpo,,,1,1,9,6,6,3,,,16,12,
1,Zaza Pachulia,,,,,12,6,4,4,,,16,14,
2,Brandon Knight,5,3,3,1,14,6,,,,3,17,,3
3,Kendall Marshall,,,,,8,6,3,3,20,,15,,
4,JR Smith,,,,,,,,,,,15,7,
5,Cole Aldrich,,,,,10,6,,,19,,12,7,
6,Tim Hardaway Jr.,4,,5,3,13,6,,,,,17,,

In [15]:
te = """ The Cleveland Cavaliers completed their sweep of the Boston Celtics with a 101-93 win on Sunday.
The Cleveland Cavaliers entered the game with a 3-0 lead in the series.
The Cleveland Cavaliers won both of the first two quarters to take a 57-36 lead at halftime.
Coach David Blatt chose to play his key players for most of the game to ensure a win.
LeBron James played 46 minutes in the game.
Kyrie Irving played 43 minutes in the game.
Kevin Love was forced from the game in the first quarter with a dislocated left shoulder.
Kelly Olynyk pulled down on Kevin Love's arm while fighting for a rebound, causing Love's injury.
Kendrick Perkins put a hard screen on Jae Crowder in the second quarter.
Kendrick Perkins was assessed a technical foul and a flagrant-1 foul for his actions.
Jae Crowder was assessed a technical foul for his response to Kendrick Perkins' screen.
J.R. Smith hit Jae Crowder in the face with a backhand in the third quarter.
J.R. Smith was given a flagrant-2 foul and automatically ejected from the game.
Jae Crowder injured his knee during the J.R. Smith incident and left the game.
Jae Crowder suffered a left knee sprain and was unable to return to the game.
The Boston Celtics outscored the Cleveland Cavaliers 25-13 in the third quarter.
The Cleveland Cavaliers carried a nine-point lead into the fourth quarter.
The Cleveland Cavaliers never let the Boston Celtics get closer than a six-point divide in the fourth quarter.
The Cleveland Cavaliers will advance to the Eastern Conference semifinals.
The Cleveland Cavaliers will play the winner of the Bulls/Bucks series in the Eastern Conference semifinals.
Kevin Love's status will be updated after he undergoes tests with the team's doctors.
J.R. Smith and Kendrick Perkins appear in line for suspensions for their actions in the game. 
Table Headers:
{
    "Team" : {
        "row_headers" : ["Cleveland Cavaliers", "Boston Celtics"],
        "column_headers" : ["Final Score", "Series Lead", "Half Time Score", "Third Quarter Score", "Fourth Quarter Score", "Advancement", "Next Opponent"]
    },
    "Player" : {
        "row_headers" : ["LeBron James", "Kyrie Irving", "Kevin Love", "Kelly Olynyk", "Kendrick Perkins", "Jae Crowder", "J.R. Smith"],
        "col_headers" : ["Minutes Played", "Injury Status", "Fouls", "Ejection Status", "Suspension Status"]
    }
}
"""

In [16]:
pprint.pprint(ask_chatgpt(text=(input+header)('\n').strip('\ '),prompt_path="prompts/rotowire_gpt4o_make_tables.txt"))

<>:1: SyntaxWarning: invalid escape sequence '\ '
<>:1: SyntaxWarning: invalid escape sequence '\ '
/var/folders/13/lbgl_ydd4jlcd4ht05rj1t9r0000gn/T/ipykernel_61914/72300718.py:1: SyntaxWarning: invalid escape sequence '\ '
  pprint.pprint(ask_chatgpt(text=(input+header)('\n').strip('\ '),prompt_path="prompts/rotowire_gpt4o_make_tables.txt"))
/var/folders/13/lbgl_ydd4jlcd4ht05rj1t9r0000gn/T/ipykernel_61914/72300718.py:1: SyntaxWarning: invalid escape sequence '\ '
  pprint.pprint(ask_chatgpt(text=(input+header)('\n').strip('\ '),prompt_path="prompts/rotowire_gpt4o_make_tables.txt"))

TypeError: 'str' object is not callable

In [ ]:
pprint.pprint(ask_gemini(
    prompt_path="prompts/rotowire_prompt_verify.txt",
    text= te.strip('\n')
))

In [ ]:
pprint.pprint(output[idx]['response'])

In [ ]:
pprint.pprint(output[idx]['input'])

In [ ]:
pprint.pprint(output[idx]['response'])

In [ ]:
df = convert_to_df(model_output_player[idx])
from tabulate import tabulate
print(tabulate(df, headers='keys', tablefmt='pretty'))
print(df)

In [ ]:
convert_to_df(gold_table_player[idx])

In [ ]:
convert_to_df(model_output_team[idx])

In [ ]:
convert_to_df(gold_table_team[idx])

In [ ]:
for i in range(0,50):
    print(i,custom_compare_tables(model_output_player[i],gold_table_player[i]))

In [ ]:
for i in range(0,50):
    print(i,compare_values(model_output_player[i],gold_table_player[i]))

## Team Table Compare

In [ ]:
for i in range(0,50):
    print(i,custom_compare_tables(model_output_team[i],gold_table_team[i]))

In [ ]:
for i in range(0,50):
    print(i,compare_values(model_output_team[i],gold_table_team[i]))